global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: [ "bot:8000" ]
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Порт, на котором node-exporter отдает метрики